// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daemon/configuration.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "daemon/configuration.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace dist_clang {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* Host_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Host_reflection_ = NULL;
const ::google::protobuf::Descriptor* Verbosity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Verbosity_reflection_ = NULL;
const ::google::protobuf::Descriptor* Verbosity_Range_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Verbosity_Range_reflection_ = NULL;
const ::google::protobuf::Descriptor* Configuration_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Configuration_reflection_ = NULL;
const ::google::protobuf::Descriptor* Configuration_Cache_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Configuration_Cache_reflection_ = NULL;
const ::google::protobuf::Descriptor* Configuration_Emitter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Configuration_Emitter_reflection_ = NULL;
const ::google::protobuf::Descriptor* Configuration_Absorber_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Configuration_Absorber_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_daemon_2fconfiguration_2eproto() {
  protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "daemon/configuration.proto");
  GOOGLE_CHECK(file != NULL);
  Host_descriptor_ = file->message_type(0);
  static const int Host_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, host_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, threads_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, disabled_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, ipv6_),
  };
  Host_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Host_descriptor_,
      Host::default_instance_,
      Host_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Host, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Host));
  Verbosity_descriptor_ = file->message_type(1);
  static const int Verbosity_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity, error_mark_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity, levels_),
  };
  Verbosity_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Verbosity_descriptor_,
      Verbosity::default_instance_,
      Verbosity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Verbosity));
  Verbosity_Range_descriptor_ = Verbosity_descriptor_->nested_type(0);
  static const int Verbosity_Range_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity_Range, right_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity_Range, left_),
  };
  Verbosity_Range_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Verbosity_Range_descriptor_,
      Verbosity_Range::default_instance_,
      Verbosity_Range_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity_Range, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Verbosity_Range, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Verbosity_Range));
  Configuration_descriptor_ = file->message_type(2);
  static const int Configuration_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, emitter_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, absorber_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, pool_capacity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, versions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, verbosity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, config_path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, cache_),
  };
  Configuration_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Configuration_descriptor_,
      Configuration::default_instance_,
      Configuration_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Configuration));
  Configuration_Cache_descriptor_ = Configuration_descriptor_->nested_type(0);
  static const int Configuration_Cache_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, sync_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, direct_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, mtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, disabled_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, snappy_),
  };
  Configuration_Cache_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Configuration_Cache_descriptor_,
      Configuration_Cache::default_instance_,
      Configuration_Cache_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Cache, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Configuration_Cache));
  Configuration_Emitter_descriptor_ = Configuration_descriptor_->nested_type(1);
  static const int Configuration_Emitter_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Emitter, socket_path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Emitter, remotes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Emitter, threads_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Emitter, only_failed_),
  };
  Configuration_Emitter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Configuration_Emitter_descriptor_,
      Configuration_Emitter::default_instance_,
      Configuration_Emitter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Emitter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Emitter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Configuration_Emitter));
  Configuration_Absorber_descriptor_ = Configuration_descriptor_->nested_type(2);
  static const int Configuration_Absorber_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Absorber, local_),
  };
  Configuration_Absorber_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Configuration_Absorber_descriptor_,
      Configuration_Absorber::default_instance_,
      Configuration_Absorber_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Absorber, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Configuration_Absorber, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Configuration_Absorber));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_daemon_2fconfiguration_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Host_descriptor_, &Host::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Verbosity_descriptor_, &Verbosity::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Verbosity_Range_descriptor_, &Verbosity_Range::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Configuration_descriptor_, &Configuration::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Configuration_Cache_descriptor_, &Configuration_Cache::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Configuration_Emitter_descriptor_, &Configuration_Emitter::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Configuration_Absorber_descriptor_, &Configuration_Absorber::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_daemon_2fconfiguration_2eproto() {
  delete Host::default_instance_;
  delete Host_reflection_;
  delete Verbosity::default_instance_;
  delete Verbosity_reflection_;
  delete Verbosity_Range::default_instance_;
  delete Verbosity_Range_reflection_;
  delete Configuration::default_instance_;
  delete Configuration_reflection_;
  delete Configuration_Cache::default_instance_;
  delete Configuration_Cache_reflection_;
  delete Configuration_Emitter::default_instance_;
  delete Configuration_Emitter_reflection_;
  delete Configuration_Absorber::default_instance_;
  delete Configuration_Absorber_reflection_;
}

void protobuf_AddDesc_daemon_2fconfiguration_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::dist_clang::proto::protobuf_AddDesc_proto_2fbase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032daemon/configuration.proto\022\020dist_clang"
    ".proto\032\020proto/base.proto\"i\n\004Host\022\014\n\004host"
    "\030\001 \002(\t\022\022\n\004port\030\002 \001(\r:\0046000\022\022\n\007threads\030\003 "
    "\001(\r:\0012\022\027\n\010disabled\030\004 \001(\010:\005false\022\022\n\004ipv6\030"
    "\005 \001(\010:\004true\"|\n\tVerbosity\022\026\n\nerror_mark\030\001"
    " \001(\r:\00220\0221\n\006levels\030\002 \003(\0132!.dist_clang.pr"
    "oto.Verbosity.Range\032$\n\005Range\022\r\n\005right\030\001 "
    "\002(\r\022\014\n\004left\030\002 \001(\r\"\240\005\n\rConfiguration\0228\n\007e"
    "mitter\030\001 \001(\0132\'.dist_clang.proto.Configur"
    "ation.Emitter\022:\n\010absorber\030\002 \001(\0132(.dist_c"
    "lang.proto.Configuration.Absorber\022\031\n\rpoo"
    "l_capacity\030\003 \001(\r:\00216\022,\n\010versions\030\004 \003(\0132\032"
    ".dist_clang.proto.Compiler\022.\n\tverbosity\030"
    "\005 \001(\0132\033.dist_clang.proto.Verbosity\022\017\n\007us"
    "er_id\030\006 \001(\r\022\023\n\013config_path\030\007 \001(\t\0224\n\005cach"
    "e\030\010 \001(\0132%.dist_clang.proto.Configuration"
    ".Cache\032\227\001\n\005Cache\022\014\n\004path\030\001 \002(\t\022\017\n\004size\030\002"
    " \001(\004:\0010\022\023\n\004sync\030\003 \001(\010:\005false\022\025\n\006direct\030\004"
    " \001(\010:\005false\022\024\n\005mtime\030\005 \001(\010:\005false\022\027\n\010dis"
    "abled\030\006 \001(\010:\005false\022\024\n\006snappy\030\007 \001(\010:\004true"
    "\032w\n\007Emitter\022\023\n\013socket_path\030\001 \002(\t\022\'\n\007remo"
    "tes\030\002 \003(\0132\026.dist_clang.proto.Host\022\022\n\007thr"
    "eads\030\003 \001(\r:\0012\022\032\n\013only_failed\030\004 \001(\010:\005fals"
    "e\0321\n\010Absorber\022%\n\005local\030\001 \002(\0132\026.dist_clan"
    "g.proto.Host", 972);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "daemon/configuration.proto", &protobuf_RegisterTypes);
  Host::default_instance_ = new Host();
  Verbosity::default_instance_ = new Verbosity();
  Verbosity_Range::default_instance_ = new Verbosity_Range();
  Configuration::default_instance_ = new Configuration();
  Configuration_Cache::default_instance_ = new Configuration_Cache();
  Configuration_Emitter::default_instance_ = new Configuration_Emitter();
  Configuration_Absorber::default_instance_ = new Configuration_Absorber();
  Host::default_instance_->InitAsDefaultInstance();
  Verbosity::default_instance_->InitAsDefaultInstance();
  Verbosity_Range::default_instance_->InitAsDefaultInstance();
  Configuration::default_instance_->InitAsDefaultInstance();
  Configuration_Cache::default_instance_->InitAsDefaultInstance();
  Configuration_Emitter::default_instance_->InitAsDefaultInstance();
  Configuration_Absorber::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_daemon_2fconfiguration_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_daemon_2fconfiguration_2eproto {
  StaticDescriptorInitializer_daemon_2fconfiguration_2eproto() {
    protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  }
} static_descriptor_initializer_daemon_2fconfiguration_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Host::kHostFieldNumber;
const int Host::kPortFieldNumber;
const int Host::kThreadsFieldNumber;
const int Host::kDisabledFieldNumber;
const int Host::kIpv6FieldNumber;
#endif  // !_MSC_VER

Host::Host()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Host)
}

void Host::InitAsDefaultInstance() {
}

Host::Host(const Host& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Host)
}

void Host::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 6000u;
  threads_ = 2u;
  disabled_ = false;
  ipv6_ = true;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Host::~Host() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Host)
  SharedDtor();
}

void Host::SharedDtor() {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete host_;
  }
  if (this != default_instance_) {
  }
}

void Host::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Host::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Host_descriptor_;
}

const Host& Host::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Host* Host::default_instance_ = NULL;

Host* Host::New() const {
  return new Host;
}

void Host::Clear() {
  if (_has_bits_[0 / 32] & 31) {
    if (has_host()) {
      if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        host_->clear();
      }
    }
    port_ = 6000u;
    threads_ = 2u;
    disabled_ = false;
    ipv6_ = true;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Host::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Host)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string host = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_host()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->host().data(), this->host().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "host");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_port;
        break;
      }

      // optional uint32 port = 2 [default = 6000];
      case 2: {
        if (tag == 16) {
         parse_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_threads;
        break;
      }

      // optional uint32 threads = 3 [default = 2];
      case 3: {
        if (tag == 24) {
         parse_threads:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &threads_)));
          set_has_threads();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_disabled;
        break;
      }

      // optional bool disabled = 4 [default = false];
      case 4: {
        if (tag == 32) {
         parse_disabled:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &disabled_)));
          set_has_disabled();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_ipv6;
        break;
      }

      // optional bool ipv6 = 5 [default = true];
      case 5: {
        if (tag == 40) {
         parse_ipv6:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ipv6_)));
          set_has_ipv6();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Host)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Host)
  return false;
#undef DO_
}

void Host::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Host)
  // required string host = 1;
  if (has_host()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->host().data(), this->host().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "host");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->host(), output);
  }

  // optional uint32 port = 2 [default = 6000];
  if (has_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->port(), output);
  }

  // optional uint32 threads = 3 [default = 2];
  if (has_threads()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->threads(), output);
  }

  // optional bool disabled = 4 [default = false];
  if (has_disabled()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->disabled(), output);
  }

  // optional bool ipv6 = 5 [default = true];
  if (has_ipv6()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->ipv6(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Host)
}

::google::protobuf::uint8* Host::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Host)
  // required string host = 1;
  if (has_host()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->host().data(), this->host().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "host");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->host(), target);
  }

  // optional uint32 port = 2 [default = 6000];
  if (has_port()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->port(), target);
  }

  // optional uint32 threads = 3 [default = 2];
  if (has_threads()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->threads(), target);
  }

  // optional bool disabled = 4 [default = false];
  if (has_disabled()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->disabled(), target);
  }

  // optional bool ipv6 = 5 [default = true];
  if (has_ipv6()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->ipv6(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Host)
  return target;
}

int Host::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string host = 1;
    if (has_host()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->host());
    }

    // optional uint32 port = 2 [default = 6000];
    if (has_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->port());
    }

    // optional uint32 threads = 3 [default = 2];
    if (has_threads()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->threads());
    }

    // optional bool disabled = 4 [default = false];
    if (has_disabled()) {
      total_size += 1 + 1;
    }

    // optional bool ipv6 = 5 [default = true];
    if (has_ipv6()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Host::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Host* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Host*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Host::MergeFrom(const Host& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_host()) {
      set_host(from.host());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
    if (from.has_threads()) {
      set_threads(from.threads());
    }
    if (from.has_disabled()) {
      set_disabled(from.disabled());
    }
    if (from.has_ipv6()) {
      set_ipv6(from.ipv6());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Host::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Host::CopyFrom(const Host& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Host::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Host::Swap(Host* other) {
  if (other != this) {
    std::swap(host_, other->host_);
    std::swap(port_, other->port_);
    std::swap(threads_, other->threads_);
    std::swap(disabled_, other->disabled_);
    std::swap(ipv6_, other->ipv6_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Host::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Host_descriptor_;
  metadata.reflection = Host_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Verbosity_Range::kRightFieldNumber;
const int Verbosity_Range::kLeftFieldNumber;
#endif  // !_MSC_VER

Verbosity_Range::Verbosity_Range()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Verbosity.Range)
}

void Verbosity_Range::InitAsDefaultInstance() {
}

Verbosity_Range::Verbosity_Range(const Verbosity_Range& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Verbosity.Range)
}

void Verbosity_Range::SharedCtor() {
  _cached_size_ = 0;
  right_ = 0u;
  left_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Verbosity_Range::~Verbosity_Range() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Verbosity.Range)
  SharedDtor();
}

void Verbosity_Range::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Verbosity_Range::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Verbosity_Range::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Verbosity_Range_descriptor_;
}

const Verbosity_Range& Verbosity_Range::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Verbosity_Range* Verbosity_Range::default_instance_ = NULL;

Verbosity_Range* Verbosity_Range::New() const {
  return new Verbosity_Range;
}

void Verbosity_Range::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Verbosity_Range*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(right_, left_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Verbosity_Range::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Verbosity.Range)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 right = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &right_)));
          set_has_right();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_left;
        break;
      }

      // optional uint32 left = 2;
      case 2: {
        if (tag == 16) {
         parse_left:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &left_)));
          set_has_left();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Verbosity.Range)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Verbosity.Range)
  return false;
#undef DO_
}

void Verbosity_Range::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Verbosity.Range)
  // required uint32 right = 1;
  if (has_right()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->right(), output);
  }

  // optional uint32 left = 2;
  if (has_left()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->left(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Verbosity.Range)
}

::google::protobuf::uint8* Verbosity_Range::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Verbosity.Range)
  // required uint32 right = 1;
  if (has_right()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->right(), target);
  }

  // optional uint32 left = 2;
  if (has_left()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->left(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Verbosity.Range)
  return target;
}

int Verbosity_Range::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 right = 1;
    if (has_right()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->right());
    }

    // optional uint32 left = 2;
    if (has_left()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->left());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Verbosity_Range::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Verbosity_Range* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Verbosity_Range*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Verbosity_Range::MergeFrom(const Verbosity_Range& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_right()) {
      set_right(from.right());
    }
    if (from.has_left()) {
      set_left(from.left());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Verbosity_Range::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Verbosity_Range::CopyFrom(const Verbosity_Range& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Verbosity_Range::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Verbosity_Range::Swap(Verbosity_Range* other) {
  if (other != this) {
    std::swap(right_, other->right_);
    std::swap(left_, other->left_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Verbosity_Range::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Verbosity_Range_descriptor_;
  metadata.reflection = Verbosity_Range_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Verbosity::kErrorMarkFieldNumber;
const int Verbosity::kLevelsFieldNumber;
#endif  // !_MSC_VER

Verbosity::Verbosity()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Verbosity)
}

void Verbosity::InitAsDefaultInstance() {
}

Verbosity::Verbosity(const Verbosity& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Verbosity)
}

void Verbosity::SharedCtor() {
  _cached_size_ = 0;
  error_mark_ = 20u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Verbosity::~Verbosity() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Verbosity)
  SharedDtor();
}

void Verbosity::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Verbosity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Verbosity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Verbosity_descriptor_;
}

const Verbosity& Verbosity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Verbosity* Verbosity::default_instance_ = NULL;

Verbosity* Verbosity::New() const {
  return new Verbosity;
}

void Verbosity::Clear() {
  error_mark_ = 20u;
  levels_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Verbosity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Verbosity)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 error_mark = 1 [default = 20];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &error_mark_)));
          set_has_error_mark();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_levels;
        break;
      }

      // repeated .dist_clang.proto.Verbosity.Range levels = 2;
      case 2: {
        if (tag == 18) {
         parse_levels:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_levels()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_levels;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Verbosity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Verbosity)
  return false;
#undef DO_
}

void Verbosity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Verbosity)
  // optional uint32 error_mark = 1 [default = 20];
  if (has_error_mark()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->error_mark(), output);
  }

  // repeated .dist_clang.proto.Verbosity.Range levels = 2;
  for (int i = 0; i < this->levels_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->levels(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Verbosity)
}

::google::protobuf::uint8* Verbosity::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Verbosity)
  // optional uint32 error_mark = 1 [default = 20];
  if (has_error_mark()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->error_mark(), target);
  }

  // repeated .dist_clang.proto.Verbosity.Range levels = 2;
  for (int i = 0; i < this->levels_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->levels(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Verbosity)
  return target;
}

int Verbosity::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 error_mark = 1 [default = 20];
    if (has_error_mark()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->error_mark());
    }

  }
  // repeated .dist_clang.proto.Verbosity.Range levels = 2;
  total_size += 1 * this->levels_size();
  for (int i = 0; i < this->levels_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->levels(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Verbosity::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Verbosity* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Verbosity*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Verbosity::MergeFrom(const Verbosity& from) {
  GOOGLE_CHECK_NE(&from, this);
  levels_.MergeFrom(from.levels_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error_mark()) {
      set_error_mark(from.error_mark());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Verbosity::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Verbosity::CopyFrom(const Verbosity& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Verbosity::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->levels())) return false;
  return true;
}

void Verbosity::Swap(Verbosity* other) {
  if (other != this) {
    std::swap(error_mark_, other->error_mark_);
    levels_.Swap(&other->levels_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Verbosity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Verbosity_descriptor_;
  metadata.reflection = Verbosity_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Configuration_Cache::kPathFieldNumber;
const int Configuration_Cache::kSizeFieldNumber;
const int Configuration_Cache::kSyncFieldNumber;
const int Configuration_Cache::kDirectFieldNumber;
const int Configuration_Cache::kMtimeFieldNumber;
const int Configuration_Cache::kDisabledFieldNumber;
const int Configuration_Cache::kSnappyFieldNumber;
#endif  // !_MSC_VER

Configuration_Cache::Configuration_Cache()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Configuration.Cache)
}

void Configuration_Cache::InitAsDefaultInstance() {
}

Configuration_Cache::Configuration_Cache(const Configuration_Cache& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Configuration.Cache)
}

void Configuration_Cache::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  size_ = GOOGLE_ULONGLONG(0);
  sync_ = false;
  direct_ = false;
  mtime_ = false;
  disabled_ = false;
  snappy_ = true;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Configuration_Cache::~Configuration_Cache() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Configuration.Cache)
  SharedDtor();
}

void Configuration_Cache::SharedDtor() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (this != default_instance_) {
  }
}

void Configuration_Cache::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Configuration_Cache::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Configuration_Cache_descriptor_;
}

const Configuration_Cache& Configuration_Cache::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Configuration_Cache* Configuration_Cache::default_instance_ = NULL;

Configuration_Cache* Configuration_Cache::New() const {
  return new Configuration_Cache;
}

void Configuration_Cache::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Configuration_Cache*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 127) {
    ZR_(size_, disabled_);
    if (has_path()) {
      if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        path_->clear();
      }
    }
    snappy_ = true;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Configuration_Cache::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Configuration.Cache)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string path = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->path().data(), this->path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_size;
        break;
      }

      // optional uint64 size = 2 [default = 0];
      case 2: {
        if (tag == 16) {
         parse_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &size_)));
          set_has_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_sync;
        break;
      }

      // optional bool sync = 3 [default = false];
      case 3: {
        if (tag == 24) {
         parse_sync:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &sync_)));
          set_has_sync();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_direct;
        break;
      }

      // optional bool direct = 4 [default = false];
      case 4: {
        if (tag == 32) {
         parse_direct:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &direct_)));
          set_has_direct();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_mtime;
        break;
      }

      // optional bool mtime = 5 [default = false];
      case 5: {
        if (tag == 40) {
         parse_mtime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &mtime_)));
          set_has_mtime();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_disabled;
        break;
      }

      // optional bool disabled = 6 [default = false];
      case 6: {
        if (tag == 48) {
         parse_disabled:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &disabled_)));
          set_has_disabled();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_snappy;
        break;
      }

      // optional bool snappy = 7 [default = true];
      case 7: {
        if (tag == 56) {
         parse_snappy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &snappy_)));
          set_has_snappy();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Configuration.Cache)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Configuration.Cache)
  return false;
#undef DO_
}

void Configuration_Cache::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Configuration.Cache)
  // required string path = 1;
  if (has_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->path(), output);
  }

  // optional uint64 size = 2 [default = 0];
  if (has_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->size(), output);
  }

  // optional bool sync = 3 [default = false];
  if (has_sync()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->sync(), output);
  }

  // optional bool direct = 4 [default = false];
  if (has_direct()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->direct(), output);
  }

  // optional bool mtime = 5 [default = false];
  if (has_mtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->mtime(), output);
  }

  // optional bool disabled = 6 [default = false];
  if (has_disabled()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->disabled(), output);
  }

  // optional bool snappy = 7 [default = true];
  if (has_snappy()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->snappy(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Configuration.Cache)
}

::google::protobuf::uint8* Configuration_Cache::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Configuration.Cache)
  // required string path = 1;
  if (has_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->path(), target);
  }

  // optional uint64 size = 2 [default = 0];
  if (has_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->size(), target);
  }

  // optional bool sync = 3 [default = false];
  if (has_sync()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->sync(), target);
  }

  // optional bool direct = 4 [default = false];
  if (has_direct()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->direct(), target);
  }

  // optional bool mtime = 5 [default = false];
  if (has_mtime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->mtime(), target);
  }

  // optional bool disabled = 6 [default = false];
  if (has_disabled()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->disabled(), target);
  }

  // optional bool snappy = 7 [default = true];
  if (has_snappy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->snappy(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Configuration.Cache)
  return target;
}

int Configuration_Cache::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string path = 1;
    if (has_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->path());
    }

    // optional uint64 size = 2 [default = 0];
    if (has_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->size());
    }

    // optional bool sync = 3 [default = false];
    if (has_sync()) {
      total_size += 1 + 1;
    }

    // optional bool direct = 4 [default = false];
    if (has_direct()) {
      total_size += 1 + 1;
    }

    // optional bool mtime = 5 [default = false];
    if (has_mtime()) {
      total_size += 1 + 1;
    }

    // optional bool disabled = 6 [default = false];
    if (has_disabled()) {
      total_size += 1 + 1;
    }

    // optional bool snappy = 7 [default = true];
    if (has_snappy()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Configuration_Cache::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Configuration_Cache* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Configuration_Cache*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Configuration_Cache::MergeFrom(const Configuration_Cache& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_path()) {
      set_path(from.path());
    }
    if (from.has_size()) {
      set_size(from.size());
    }
    if (from.has_sync()) {
      set_sync(from.sync());
    }
    if (from.has_direct()) {
      set_direct(from.direct());
    }
    if (from.has_mtime()) {
      set_mtime(from.mtime());
    }
    if (from.has_disabled()) {
      set_disabled(from.disabled());
    }
    if (from.has_snappy()) {
      set_snappy(from.snappy());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Configuration_Cache::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Configuration_Cache::CopyFrom(const Configuration_Cache& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Configuration_Cache::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Configuration_Cache::Swap(Configuration_Cache* other) {
  if (other != this) {
    std::swap(path_, other->path_);
    std::swap(size_, other->size_);
    std::swap(sync_, other->sync_);
    std::swap(direct_, other->direct_);
    std::swap(mtime_, other->mtime_);
    std::swap(disabled_, other->disabled_);
    std::swap(snappy_, other->snappy_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Configuration_Cache::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Configuration_Cache_descriptor_;
  metadata.reflection = Configuration_Cache_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Configuration_Emitter::kSocketPathFieldNumber;
const int Configuration_Emitter::kRemotesFieldNumber;
const int Configuration_Emitter::kThreadsFieldNumber;
const int Configuration_Emitter::kOnlyFailedFieldNumber;
#endif  // !_MSC_VER

Configuration_Emitter::Configuration_Emitter()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Configuration.Emitter)
}

void Configuration_Emitter::InitAsDefaultInstance() {
}

Configuration_Emitter::Configuration_Emitter(const Configuration_Emitter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Configuration.Emitter)
}

void Configuration_Emitter::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  socket_path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  threads_ = 2u;
  only_failed_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Configuration_Emitter::~Configuration_Emitter() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Configuration.Emitter)
  SharedDtor();
}

void Configuration_Emitter::SharedDtor() {
  if (socket_path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete socket_path_;
  }
  if (this != default_instance_) {
  }
}

void Configuration_Emitter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Configuration_Emitter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Configuration_Emitter_descriptor_;
}

const Configuration_Emitter& Configuration_Emitter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Configuration_Emitter* Configuration_Emitter::default_instance_ = NULL;

Configuration_Emitter* Configuration_Emitter::New() const {
  return new Configuration_Emitter;
}

void Configuration_Emitter::Clear() {
  if (_has_bits_[0 / 32] & 13) {
    if (has_socket_path()) {
      if (socket_path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        socket_path_->clear();
      }
    }
    threads_ = 2u;
    only_failed_ = false;
  }
  remotes_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Configuration_Emitter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Configuration.Emitter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string socket_path = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_socket_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->socket_path().data(), this->socket_path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "socket_path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_remotes;
        break;
      }

      // repeated .dist_clang.proto.Host remotes = 2;
      case 2: {
        if (tag == 18) {
         parse_remotes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_remotes()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_remotes;
        if (input->ExpectTag(24)) goto parse_threads;
        break;
      }

      // optional uint32 threads = 3 [default = 2];
      case 3: {
        if (tag == 24) {
         parse_threads:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &threads_)));
          set_has_threads();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_only_failed;
        break;
      }

      // optional bool only_failed = 4 [default = false];
      case 4: {
        if (tag == 32) {
         parse_only_failed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &only_failed_)));
          set_has_only_failed();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Configuration.Emitter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Configuration.Emitter)
  return false;
#undef DO_
}

void Configuration_Emitter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Configuration.Emitter)
  // required string socket_path = 1;
  if (has_socket_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->socket_path().data(), this->socket_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "socket_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->socket_path(), output);
  }

  // repeated .dist_clang.proto.Host remotes = 2;
  for (int i = 0; i < this->remotes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->remotes(i), output);
  }

  // optional uint32 threads = 3 [default = 2];
  if (has_threads()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->threads(), output);
  }

  // optional bool only_failed = 4 [default = false];
  if (has_only_failed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->only_failed(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Configuration.Emitter)
}

::google::protobuf::uint8* Configuration_Emitter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Configuration.Emitter)
  // required string socket_path = 1;
  if (has_socket_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->socket_path().data(), this->socket_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "socket_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->socket_path(), target);
  }

  // repeated .dist_clang.proto.Host remotes = 2;
  for (int i = 0; i < this->remotes_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->remotes(i), target);
  }

  // optional uint32 threads = 3 [default = 2];
  if (has_threads()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->threads(), target);
  }

  // optional bool only_failed = 4 [default = false];
  if (has_only_failed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->only_failed(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Configuration.Emitter)
  return target;
}

int Configuration_Emitter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string socket_path = 1;
    if (has_socket_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->socket_path());
    }

    // optional uint32 threads = 3 [default = 2];
    if (has_threads()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->threads());
    }

    // optional bool only_failed = 4 [default = false];
    if (has_only_failed()) {
      total_size += 1 + 1;
    }

  }
  // repeated .dist_clang.proto.Host remotes = 2;
  total_size += 1 * this->remotes_size();
  for (int i = 0; i < this->remotes_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->remotes(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Configuration_Emitter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Configuration_Emitter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Configuration_Emitter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Configuration_Emitter::MergeFrom(const Configuration_Emitter& from) {
  GOOGLE_CHECK_NE(&from, this);
  remotes_.MergeFrom(from.remotes_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_socket_path()) {
      set_socket_path(from.socket_path());
    }
    if (from.has_threads()) {
      set_threads(from.threads());
    }
    if (from.has_only_failed()) {
      set_only_failed(from.only_failed());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Configuration_Emitter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Configuration_Emitter::CopyFrom(const Configuration_Emitter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Configuration_Emitter::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->remotes())) return false;
  return true;
}

void Configuration_Emitter::Swap(Configuration_Emitter* other) {
  if (other != this) {
    std::swap(socket_path_, other->socket_path_);
    remotes_.Swap(&other->remotes_);
    std::swap(threads_, other->threads_);
    std::swap(only_failed_, other->only_failed_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Configuration_Emitter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Configuration_Emitter_descriptor_;
  metadata.reflection = Configuration_Emitter_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Configuration_Absorber::kLocalFieldNumber;
#endif  // !_MSC_VER

Configuration_Absorber::Configuration_Absorber()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Configuration.Absorber)
}

void Configuration_Absorber::InitAsDefaultInstance() {
  local_ = const_cast< ::dist_clang::proto::Host*>(&::dist_clang::proto::Host::default_instance());
}

Configuration_Absorber::Configuration_Absorber(const Configuration_Absorber& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Configuration.Absorber)
}

void Configuration_Absorber::SharedCtor() {
  _cached_size_ = 0;
  local_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Configuration_Absorber::~Configuration_Absorber() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Configuration.Absorber)
  SharedDtor();
}

void Configuration_Absorber::SharedDtor() {
  if (this != default_instance_) {
    delete local_;
  }
}

void Configuration_Absorber::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Configuration_Absorber::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Configuration_Absorber_descriptor_;
}

const Configuration_Absorber& Configuration_Absorber::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Configuration_Absorber* Configuration_Absorber::default_instance_ = NULL;

Configuration_Absorber* Configuration_Absorber::New() const {
  return new Configuration_Absorber;
}

void Configuration_Absorber::Clear() {
  if (has_local()) {
    if (local_ != NULL) local_->::dist_clang::proto::Host::Clear();
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Configuration_Absorber::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Configuration.Absorber)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .dist_clang.proto.Host local = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_local()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Configuration.Absorber)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Configuration.Absorber)
  return false;
#undef DO_
}

void Configuration_Absorber::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Configuration.Absorber)
  // required .dist_clang.proto.Host local = 1;
  if (has_local()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->local(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Configuration.Absorber)
}

::google::protobuf::uint8* Configuration_Absorber::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Configuration.Absorber)
  // required .dist_clang.proto.Host local = 1;
  if (has_local()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->local(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Configuration.Absorber)
  return target;
}

int Configuration_Absorber::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .dist_clang.proto.Host local = 1;
    if (has_local()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->local());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Configuration_Absorber::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Configuration_Absorber* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Configuration_Absorber*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Configuration_Absorber::MergeFrom(const Configuration_Absorber& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_local()) {
      mutable_local()->::dist_clang::proto::Host::MergeFrom(from.local());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Configuration_Absorber::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Configuration_Absorber::CopyFrom(const Configuration_Absorber& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Configuration_Absorber::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_local()) {
    if (!this->local().IsInitialized()) return false;
  }
  return true;
}

void Configuration_Absorber::Swap(Configuration_Absorber* other) {
  if (other != this) {
    std::swap(local_, other->local_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Configuration_Absorber::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Configuration_Absorber_descriptor_;
  metadata.reflection = Configuration_Absorber_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Configuration::kEmitterFieldNumber;
const int Configuration::kAbsorberFieldNumber;
const int Configuration::kPoolCapacityFieldNumber;
const int Configuration::kVersionsFieldNumber;
const int Configuration::kVerbosityFieldNumber;
const int Configuration::kUserIdFieldNumber;
const int Configuration::kConfigPathFieldNumber;
const int Configuration::kCacheFieldNumber;
#endif  // !_MSC_VER

Configuration::Configuration()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dist_clang.proto.Configuration)
}

void Configuration::InitAsDefaultInstance() {
  emitter_ = const_cast< ::dist_clang::proto::Configuration_Emitter*>(&::dist_clang::proto::Configuration_Emitter::default_instance());
  absorber_ = const_cast< ::dist_clang::proto::Configuration_Absorber*>(&::dist_clang::proto::Configuration_Absorber::default_instance());
  verbosity_ = const_cast< ::dist_clang::proto::Verbosity*>(&::dist_clang::proto::Verbosity::default_instance());
  cache_ = const_cast< ::dist_clang::proto::Configuration_Cache*>(&::dist_clang::proto::Configuration_Cache::default_instance());
}

Configuration::Configuration(const Configuration& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dist_clang.proto.Configuration)
}

void Configuration::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  emitter_ = NULL;
  absorber_ = NULL;
  pool_capacity_ = 16u;
  verbosity_ = NULL;
  user_id_ = 0u;
  config_path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cache_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Configuration::~Configuration() {
  // @@protoc_insertion_point(destructor:dist_clang.proto.Configuration)
  SharedDtor();
}

void Configuration::SharedDtor() {
  if (config_path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete config_path_;
  }
  if (this != default_instance_) {
    delete emitter_;
    delete absorber_;
    delete verbosity_;
    delete cache_;
  }
}

void Configuration::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Configuration::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Configuration_descriptor_;
}

const Configuration& Configuration::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_daemon_2fconfiguration_2eproto();
  return *default_instance_;
}

Configuration* Configuration::default_instance_ = NULL;

Configuration* Configuration::New() const {
  return new Configuration;
}

void Configuration::Clear() {
  if (_has_bits_[0 / 32] & 247) {
    if (has_emitter()) {
      if (emitter_ != NULL) emitter_->::dist_clang::proto::Configuration_Emitter::Clear();
    }
    if (has_absorber()) {
      if (absorber_ != NULL) absorber_->::dist_clang::proto::Configuration_Absorber::Clear();
    }
    pool_capacity_ = 16u;
    if (has_verbosity()) {
      if (verbosity_ != NULL) verbosity_->::dist_clang::proto::Verbosity::Clear();
    }
    user_id_ = 0u;
    if (has_config_path()) {
      if (config_path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        config_path_->clear();
      }
    }
    if (has_cache()) {
      if (cache_ != NULL) cache_->::dist_clang::proto::Configuration_Cache::Clear();
    }
  }
  versions_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Configuration::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dist_clang.proto.Configuration)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .dist_clang.proto.Configuration.Emitter emitter = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_emitter()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_absorber;
        break;
      }

      // optional .dist_clang.proto.Configuration.Absorber absorber = 2;
      case 2: {
        if (tag == 18) {
         parse_absorber:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_absorber()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_pool_capacity;
        break;
      }

      // optional uint32 pool_capacity = 3 [default = 16];
      case 3: {
        if (tag == 24) {
         parse_pool_capacity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pool_capacity_)));
          set_has_pool_capacity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_versions;
        break;
      }

      // repeated .dist_clang.proto.Compiler versions = 4;
      case 4: {
        if (tag == 34) {
         parse_versions:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_versions()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_versions;
        if (input->ExpectTag(42)) goto parse_verbosity;
        break;
      }

      // optional .dist_clang.proto.Verbosity verbosity = 5;
      case 5: {
        if (tag == 42) {
         parse_verbosity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_verbosity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_user_id;
        break;
      }

      // optional uint32 user_id = 6;
      case 6: {
        if (tag == 48) {
         parse_user_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_config_path;
        break;
      }

      // optional string config_path = 7;
      case 7: {
        if (tag == 58) {
         parse_config_path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_config_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->config_path().data(), this->config_path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config_path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_cache;
        break;
      }

      // optional .dist_clang.proto.Configuration.Cache cache = 8;
      case 8: {
        if (tag == 66) {
         parse_cache:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_cache()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dist_clang.proto.Configuration)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dist_clang.proto.Configuration)
  return false;
#undef DO_
}

void Configuration::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dist_clang.proto.Configuration)
  // optional .dist_clang.proto.Configuration.Emitter emitter = 1;
  if (has_emitter()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->emitter(), output);
  }

  // optional .dist_clang.proto.Configuration.Absorber absorber = 2;
  if (has_absorber()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->absorber(), output);
  }

  // optional uint32 pool_capacity = 3 [default = 16];
  if (has_pool_capacity()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->pool_capacity(), output);
  }

  // repeated .dist_clang.proto.Compiler versions = 4;
  for (int i = 0; i < this->versions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->versions(i), output);
  }

  // optional .dist_clang.proto.Verbosity verbosity = 5;
  if (has_verbosity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->verbosity(), output);
  }

  // optional uint32 user_id = 6;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->user_id(), output);
  }

  // optional string config_path = 7;
  if (has_config_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->config_path().data(), this->config_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->config_path(), output);
  }

  // optional .dist_clang.proto.Configuration.Cache cache = 8;
  if (has_cache()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, this->cache(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dist_clang.proto.Configuration)
}

::google::protobuf::uint8* Configuration::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dist_clang.proto.Configuration)
  // optional .dist_clang.proto.Configuration.Emitter emitter = 1;
  if (has_emitter()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->emitter(), target);
  }

  // optional .dist_clang.proto.Configuration.Absorber absorber = 2;
  if (has_absorber()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->absorber(), target);
  }

  // optional uint32 pool_capacity = 3 [default = 16];
  if (has_pool_capacity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->pool_capacity(), target);
  }

  // repeated .dist_clang.proto.Compiler versions = 4;
  for (int i = 0; i < this->versions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->versions(i), target);
  }

  // optional .dist_clang.proto.Verbosity verbosity = 5;
  if (has_verbosity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->verbosity(), target);
  }

  // optional uint32 user_id = 6;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->user_id(), target);
  }

  // optional string config_path = 7;
  if (has_config_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->config_path().data(), this->config_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->config_path(), target);
  }

  // optional .dist_clang.proto.Configuration.Cache cache = 8;
  if (has_cache()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, this->cache(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dist_clang.proto.Configuration)
  return target;
}

int Configuration::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .dist_clang.proto.Configuration.Emitter emitter = 1;
    if (has_emitter()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->emitter());
    }

    // optional .dist_clang.proto.Configuration.Absorber absorber = 2;
    if (has_absorber()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->absorber());
    }

    // optional uint32 pool_capacity = 3 [default = 16];
    if (has_pool_capacity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->pool_capacity());
    }

    // optional .dist_clang.proto.Verbosity verbosity = 5;
    if (has_verbosity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->verbosity());
    }

    // optional uint32 user_id = 6;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // optional string config_path = 7;
    if (has_config_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->config_path());
    }

    // optional .dist_clang.proto.Configuration.Cache cache = 8;
    if (has_cache()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->cache());
    }

  }
  // repeated .dist_clang.proto.Compiler versions = 4;
  total_size += 1 * this->versions_size();
  for (int i = 0; i < this->versions_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->versions(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Configuration::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Configuration* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Configuration*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Configuration::MergeFrom(const Configuration& from) {
  GOOGLE_CHECK_NE(&from, this);
  versions_.MergeFrom(from.versions_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_emitter()) {
      mutable_emitter()->::dist_clang::proto::Configuration_Emitter::MergeFrom(from.emitter());
    }
    if (from.has_absorber()) {
      mutable_absorber()->::dist_clang::proto::Configuration_Absorber::MergeFrom(from.absorber());
    }
    if (from.has_pool_capacity()) {
      set_pool_capacity(from.pool_capacity());
    }
    if (from.has_verbosity()) {
      mutable_verbosity()->::dist_clang::proto::Verbosity::MergeFrom(from.verbosity());
    }
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_config_path()) {
      set_config_path(from.config_path());
    }
    if (from.has_cache()) {
      mutable_cache()->::dist_clang::proto::Configuration_Cache::MergeFrom(from.cache());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Configuration::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Configuration::CopyFrom(const Configuration& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Configuration::IsInitialized() const {

  if (has_emitter()) {
    if (!this->emitter().IsInitialized()) return false;
  }
  if (has_absorber()) {
    if (!this->absorber().IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->versions())) return false;
  if (has_verbosity()) {
    if (!this->verbosity().IsInitialized()) return false;
  }
  if (has_cache()) {
    if (!this->cache().IsInitialized()) return false;
  }
  return true;
}

void Configuration::Swap(Configuration* other) {
  if (other != this) {
    std::swap(emitter_, other->emitter_);
    std::swap(absorber_, other->absorber_);
    std::swap(pool_capacity_, other->pool_capacity_);
    versions_.Swap(&other->versions_);
    std::swap(verbosity_, other->verbosity_);
    std::swap(user_id_, other->user_id_);
    std::swap(config_path_, other->config_path_);
    std::swap(cache_, other->cache_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Configuration::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Configuration_descriptor_;
  metadata.reflection = Configuration_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace dist_clang

// @@protoc_insertion_point(global_scope)
