// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/base.proto

#ifndef PROTOBUF_proto_2fbase_2eproto__INCLUDED
#define PROTOBUF_proto_2fbase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dist_clang {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fbase_2eproto();
void protobuf_AssignDesc_proto_2fbase_2eproto();
void protobuf_ShutdownFile_proto_2fbase_2eproto();

class Plugin;
class Compiler;

// ===================================================================

class Plugin : public ::google::protobuf::Message {
 public:
  Plugin();
  virtual ~Plugin();

  Plugin(const Plugin& from);

  inline Plugin& operator=(const Plugin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Plugin& default_instance();

  void Swap(Plugin* other);

  // implements Message ----------------------------------------------

  Plugin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Plugin& from);
  void MergeFrom(const Plugin& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string path = 2;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 2;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:dist_clang.proto.Plugin)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_path();
  inline void clear_has_path();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* path_;
  friend void  protobuf_AddDesc_proto_2fbase_2eproto();
  friend void protobuf_AssignDesc_proto_2fbase_2eproto();
  friend void protobuf_ShutdownFile_proto_2fbase_2eproto();

  void InitAsDefaultInstance();
  static Plugin* default_instance_;
};
// -------------------------------------------------------------------

class Compiler : public ::google::protobuf::Message {
 public:
  Compiler();
  virtual ~Compiler();

  Compiler(const Compiler& from);

  inline Compiler& operator=(const Compiler& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Compiler& default_instance();

  void Swap(Compiler* other);

  // implements Message ----------------------------------------------

  Compiler* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Compiler& from);
  void MergeFrom(const Compiler& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline const ::std::string& version() const;
  inline void set_version(const ::std::string& value);
  inline void set_version(const char* value);
  inline void set_version(const char* value, size_t size);
  inline ::std::string* mutable_version();
  inline ::std::string* release_version();
  inline void set_allocated_version(::std::string* version);

  // optional string path = 2;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 2;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // repeated .dist_clang.proto.Plugin plugins = 3;
  inline int plugins_size() const;
  inline void clear_plugins();
  static const int kPluginsFieldNumber = 3;
  inline const ::dist_clang::proto::Plugin& plugins(int index) const;
  inline ::dist_clang::proto::Plugin* mutable_plugins(int index);
  inline ::dist_clang::proto::Plugin* add_plugins();
  inline const ::google::protobuf::RepeatedPtrField< ::dist_clang::proto::Plugin >&
      plugins() const;
  inline ::google::protobuf::RepeatedPtrField< ::dist_clang::proto::Plugin >*
      mutable_plugins();

  // @@protoc_insertion_point(class_scope:dist_clang.proto.Compiler)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_path();
  inline void clear_has_path();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* version_;
  ::std::string* path_;
  ::google::protobuf::RepeatedPtrField< ::dist_clang::proto::Plugin > plugins_;
  friend void  protobuf_AddDesc_proto_2fbase_2eproto();
  friend void protobuf_AssignDesc_proto_2fbase_2eproto();
  friend void protobuf_ShutdownFile_proto_2fbase_2eproto();

  void InitAsDefaultInstance();
  static Compiler* default_instance_;
};
// ===================================================================


// ===================================================================

// Plugin

// required string name = 1;
inline bool Plugin::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Plugin::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Plugin::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Plugin::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Plugin::name() const {
  // @@protoc_insertion_point(field_get:dist_clang.proto.Plugin.name)
  return *name_;
}
inline void Plugin::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:dist_clang.proto.Plugin.name)
}
inline void Plugin::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:dist_clang.proto.Plugin.name)
}
inline void Plugin::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dist_clang.proto.Plugin.name)
}
inline ::std::string* Plugin::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dist_clang.proto.Plugin.name)
  return name_;
}
inline ::std::string* Plugin::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Plugin::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dist_clang.proto.Plugin.name)
}

// optional string path = 2;
inline bool Plugin::has_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Plugin::set_has_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Plugin::clear_has_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Plugin::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& Plugin::path() const {
  // @@protoc_insertion_point(field_get:dist_clang.proto.Plugin.path)
  return *path_;
}
inline void Plugin::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:dist_clang.proto.Plugin.path)
}
inline void Plugin::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:dist_clang.proto.Plugin.path)
}
inline void Plugin::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dist_clang.proto.Plugin.path)
}
inline ::std::string* Plugin::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dist_clang.proto.Plugin.path)
  return path_;
}
inline ::std::string* Plugin::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Plugin::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dist_clang.proto.Plugin.path)
}

// -------------------------------------------------------------------

// Compiler

// required string version = 1;
inline bool Compiler::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Compiler::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Compiler::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Compiler::clear_version() {
  if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    version_->clear();
  }
  clear_has_version();
}
inline const ::std::string& Compiler::version() const {
  // @@protoc_insertion_point(field_get:dist_clang.proto.Compiler.version)
  return *version_;
}
inline void Compiler::set_version(const ::std::string& value) {
  set_has_version();
  if (version_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    version_ = new ::std::string;
  }
  version_->assign(value);
  // @@protoc_insertion_point(field_set:dist_clang.proto.Compiler.version)
}
inline void Compiler::set_version(const char* value) {
  set_has_version();
  if (version_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    version_ = new ::std::string;
  }
  version_->assign(value);
  // @@protoc_insertion_point(field_set_char:dist_clang.proto.Compiler.version)
}
inline void Compiler::set_version(const char* value, size_t size) {
  set_has_version();
  if (version_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    version_ = new ::std::string;
  }
  version_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dist_clang.proto.Compiler.version)
}
inline ::std::string* Compiler::mutable_version() {
  set_has_version();
  if (version_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    version_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dist_clang.proto.Compiler.version)
  return version_;
}
inline ::std::string* Compiler::release_version() {
  clear_has_version();
  if (version_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = version_;
    version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Compiler::set_allocated_version(::std::string* version) {
  if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete version_;
  }
  if (version) {
    set_has_version();
    version_ = version;
  } else {
    clear_has_version();
    version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dist_clang.proto.Compiler.version)
}

// optional string path = 2;
inline bool Compiler::has_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Compiler::set_has_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Compiler::clear_has_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Compiler::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& Compiler::path() const {
  // @@protoc_insertion_point(field_get:dist_clang.proto.Compiler.path)
  return *path_;
}
inline void Compiler::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:dist_clang.proto.Compiler.path)
}
inline void Compiler::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:dist_clang.proto.Compiler.path)
}
inline void Compiler::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dist_clang.proto.Compiler.path)
}
inline ::std::string* Compiler::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dist_clang.proto.Compiler.path)
  return path_;
}
inline ::std::string* Compiler::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Compiler::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dist_clang.proto.Compiler.path)
}

// repeated .dist_clang.proto.Plugin plugins = 3;
inline int Compiler::plugins_size() const {
  return plugins_.size();
}
inline void Compiler::clear_plugins() {
  plugins_.Clear();
}
inline const ::dist_clang::proto::Plugin& Compiler::plugins(int index) const {
  // @@protoc_insertion_point(field_get:dist_clang.proto.Compiler.plugins)
  return plugins_.Get(index);
}
inline ::dist_clang::proto::Plugin* Compiler::mutable_plugins(int index) {
  // @@protoc_insertion_point(field_mutable:dist_clang.proto.Compiler.plugins)
  return plugins_.Mutable(index);
}
inline ::dist_clang::proto::Plugin* Compiler::add_plugins() {
  // @@protoc_insertion_point(field_add:dist_clang.proto.Compiler.plugins)
  return plugins_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dist_clang::proto::Plugin >&
Compiler::plugins() const {
  // @@protoc_insertion_point(field_list:dist_clang.proto.Compiler.plugins)
  return plugins_;
}
inline ::google::protobuf::RepeatedPtrField< ::dist_clang::proto::Plugin >*
Compiler::mutable_plugins() {
  // @@protoc_insertion_point(field_mutable_list:dist_clang.proto.Compiler.plugins)
  return &plugins_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace dist_clang

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fbase_2eproto__INCLUDED
