#!/bin/sh

### BEGIN INIT INFO
# Provides:        clangd
# Required-Start:  $network $local_fs $syslog
# Required-Stop:   $network $local_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start Clangd daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/bin/dist-clang
NAME=clangd
DAEMON=/usr/bin/dist-clang/${NAME}
DESC="Distributed Clang Daemon"
DAEMON_ARGS="--daemon --config /etc/${NAME}.conf"

set -e

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

clangd_start() {
  log_daemon_msg "Starting clangd"
  start-stop-daemon --start -o -x $DAEMON -n $NAME -- $DAEMON_ARGS 
  log_end_msg $?
}

clangd_stop() {
  log_daemon_msg "Stopping clangd"
  start-stop-daemon --stop -o -x $DAEMON -n $NAME
  log_end_msg $?
}

case "$1" in
  start|stop)
    ${NAME}_${1}
    ;;
  restart|reload|force-reload)
    ${NAME}_stop
    ${NAME}_start
    ;;
  force-stop)
    ${NAME}_stop
    sleep 3
    killall ${NAME} || true
    sleep 3
    killall -9 ${NAME} || true
    ;;
  status)
    status_of_proc "$DAEMON" "system-wide ${NAME}" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/${NAME} {start|stop|force-stop|restart|reload|force-reload|status}"
    exit 1
    ;;
esac

exit 0
